### ISSUE TITLE
Cannot install tzf in Ruby 3.3.1

### ISSUE THREAD

**Issue by JamesChevalier** [HarlemSquirrel/tzf-rb#21]
This same issue happens directly on my M2 Mac, but giving a Docker reproduction (as opposed an `asdf` setup etc etc) seemed like it would be easier for you.

Dockerfile:

```
FROM ruby:3.3
WORKDIR /app
RUN apt-get update -qq && \
  apt-get upgrade -y && \
  apt-get install -y libclang-dev
COPY Gemfile /app
RUN bundle install
```

Gemfile:

```
source "https://rubygems.org"
gem "tzf"
```

Error:

<details>
<summary>Stable API is needed but could not find a candidate. Try enabling the `stable-api-compiled-fallback` feature in rb-sys.</summary>

```
23.84 error: 'rustfmt' is not installed for the toolchain
23.84 'stable-aarch64-unknown-linux-gnu'.
23.84   To install, run `rustup component add rustfmt`
23.84 thread 'main' panicked at
23.84 /usr/local/bundle/gems/tzf-0.4.5/ext/tzf/.rb-sys/stable/cargo/registry/src/index.crates.io-6f17d22bba15001f/rb-sys-0.9.82/build/main.rs:64:59:
23.84 called `Result::unwrap()` on an `Err` value: "Stable API is needed but could
23.84 not find a candidate. Try enabling the `stable-api-compiled-fallback` feature in
23.84 rb-sys."
23.84   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
23.84 make: *** [Makefile:566: target/release/libtzf.so] Error 101
23.84 
23.84 make failed, exit code 2
23.84 
23.84 Gem files will remain installed in /usr/local/bundle/gems/tzf-0.4.5 for
23.84 inspection.
23.84 Results logged to
23.84 /usr/local/bundle/extensions/aarch64-linux/3.3.0/tzf-0.4.5/gem_make.out
23.84 
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
23.84 /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
23.84 build_extensions'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
23.84   /usr/local/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
23.84 /usr/local/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in
23.84 `build_extensions'
23.84   /usr/local/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in `install'
23.84   /usr/local/lib/ruby/3.3.0/bundler/source/rubygems.rb:205:in `install'
23.84   /usr/local/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
23.84 /usr/local/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in
23.84 `install_from_spec'
23.84 /usr/local/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in
23.84 `do_install'
23.84 /usr/local/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in
23.84 `block in worker_pool'
23.84   /usr/local/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
23.84   /usr/local/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
23.84   <internal:kernel>:187:in `loop'
23.84   /usr/local/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
23.84 /usr/local/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in
23.84 create_threads'
23.84 
23.84 An error occurred while installing tzf (0.4.5), and Bundler cannot continue.
23.84 
23.84 In Gemfile:
23.84   tzf
------
Dockerfile.tzf:7
--------------------
   5 |       apt-get install -y libclang-dev
   6 |     COPY Gemfile.tzf /app/Gemfile
   7 | >>> RUN bundle install
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c bundle install" did not complete successfully: exit code: 5
```
</details>

I did try enabling Rust backtrace, but the only info it seemed to add was:

```
  stack backtrace:
     0: _rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: build_script_main::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I don't _think_ this is related to https://github.com/HarlemSquirrel/tzf-rb/issues/13 but I want to bring that up just in case.
I tested your `oxi-test` suggestion from that issue, and did not receive this error.

oxi-test Gemfile:

```
source "https://rubygems.org"
gem "rb_sys", "0.9.97"
gem "oxi-test", git: "https://github.com/oxidize-rb/oxi-test", branch: :main
```

**Comment by JamesChevalier** [comment]
I found your [Docker setup](https://github.com/HarlemSquirrel/tzf-rb/tree/main/docker) in this repo and did some testing with it. I found that the build process works but the gem still cannot be installed while within that Docker image.

Building the image with `docker build -t tzf -f docker/Dockerfile .` worked successfully (the tzf gem would build/install as expected).

Opening shell access to the container with `docker run -it --rm tzf bash`, then removing the tzf gem with `gem uninstall tzf`, then installing the remote tzf gem with `gem install tzf` would reproduce the failure.

**Comment by HarlemSquirrel** [comment]
Does it work if you install the gem pointing to latest main branch?

**Comment by JamesChevalier** [comment]
Yeah, setting the Gemfile to `gem "tzf", git: "https://github.com/HarlemSquirrel/tzf-rb.git"` does get the gem to install in both the Docker environment as well as my local Mac environment.

**Comment by HarlemSquirrel** [comment]
Ok awesome, will publish a new version ASAP

**Comment by HarlemSquirrel** [comment]
@JamesChevalier Let me know if the latest version https://rubygems.org/gems/tzf/versions/1.0.0 works OK for you.

**Comment by JamesChevalier** [comment]
Installed/worked perfectly both on my local Mac & the Docker environment.
Thanks, and congratulations on the 1.0 release milestone!
